"""add tagesraetsel_streaks

Revision ID: e7a9205c2560
Revises: f59716b84cde
Create Date: 2026-04-28 23:51:18.632764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a9205c2560'
down_revision: Union[str, Sequence[str], None] = 'f59716b84cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagesraetsel_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('puzzle_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'date', name='uq_streak_session_date')
    )
    with op.batch_alter_table('tagesraetsel_streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tagesraetsel_streaks_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tagesraetsel_streaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tagesraetsel_streaks_session_id'))

    op.drop_table('tagesraetsel_streaks')
    # ### end Alembic commands ###
